services:
  bbc-cron:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bbc-cron
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DRY_RUN=${DRY_RUN:-false}
      - SHARED_QUEUE_PATH=/app/shared/queue.json
    volumes:
      - ./crontab:/app/crontab:ro
      - ./shared:/app/shared
      - ./data:/app/data
      - ./.env:/app/.env